[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit seesaw Library@^1.7.7
    adafruit/Adafruit BusIO@^1.16.1
    fastled/FastLED@^3.7.0
