; I2C Scanner for ESP32-C3
[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps = 
    adafruit/Adafruit seesaw Library@^1.7.7
    adafruit/Adafruit BusIO@^1.16.1