[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit seesaw Library@^1.7.7
    adafruit/Adafruit BusIO@^1.16.1
    fastled/FastLED@^3.7.0
    adafruit/Adafruit GFX Library@^1.11.0
    prenticedavid/MCUFRIEND_kbv@^3.0.0
    SPI
    Wire

build_flags = 
    -DCORE_DEBUG_LEVEL=0












